#!/bin/php
<?php
include_once ("/dse/bin/dse_cli_functions.php");
include_once ("/dse/include/system_stat_functions.php");

$dse_sysstats_power_array=dse_sysstats_power();
$VoltageStr=number_format($dse_sysstats_power_array['BatteryVoltage']/1000,2)."v";
$AmperageStr=number_format($dse_sysstats_power_array['BatteryCurrentCapacity']/1000,2)."Ah";
$TemperatureStr=number_format($dse_sysstats_power_array['BatteryTemperature']/32,2)." deg C";

print "Battery: ".$dse_sysstats_power_array['BatteryPercentStr']
	."   ". $dse_sysstats_power_array['BatteryTemperatureStr']
	."   ". $dse_sysstats_power_array['BatteryVoltageStr']
	."   ". $dse_sysstats_power_array['BatteryAmperageStr']
	."   ". $dse_sysstats_power_array['BatteryCycleCount'] ." cycles"
	."\n";
	
	
print "Mouse Battery: ".$dse_sysstats_power_array['MouseBatteryPercentStr']."\n";

print "Keyboard Battery: ".$dse_sysstats_power_array['KeyboardBatteryPercentStr']."\n";

if($dse_sysstats_power_array['TrackpadBatteryPercent']!=""){
	print "Trackpad Battery: ".$dse_sysstats_power_array['TrackpadBatteryPercentStr']."\n";
}

?>