<?php


$vars[DSE][FontChars]=array(
	'A'=>array(	'   /\   ',
				'  /  \  ',
				' |____| ',
				' |    | ',
				' |    | ',
		),
	'B'=>array(	' ____  ',
				' |   \ ',
				' |___/ ',
				' |   \ ',
				' |___/ ',
		),
	'C'=>array(	'  ___  ',
				' /   \ ',
				' |     ',
				' |     ',
				' \___/ ',
		),
	'D'=>array(	' ____  ',
				' |   \ ',
				' |    |',
				' |    |',
				' |___/ ',
		),
	'E'=>array(	' _____ ',
				' |     ',
				' |___  ',
				' |     ',
				' |____ ',
		),
	'F'=>array(	' _____ ',
				' |     ',
				' |___  ',
				' |     ',
				' |     ',
		),
	'G'=>array(	'  ___   ',
				' /   ^  ',
				' |  ___ ',
				' |   /  ',
				'  \_/   ',
		),
	'H'=>array(	' |   | ',
				' |   | ',
				' |---| ',
				' |   | ',
				' |   | ',
		),
	'I'=>array(	' ___ ',
				'  |  ',
				'  |  ',
				' _|_ ',
				'     ',
		),
	'J'=>array(	'    __ ',
				'     | ',
				'     | ',
				' |   | ',
				'  \_/  ',
		),
	'K'=>array(	' |  / ',
				' | /  ',
				' |K   ',
				' | \  ',
				' |  \ ',
		),
	'L'=>array(	'      ',
				' |    ',
				' |    ',
				' |    ',
				' L___ ',
		),
	'M'=>array(	'      ',
				' |\ /| ',
				' | V | ',
				' |   | ',
				'       ',
		),
	'N'=>array(	'       ',
				' |\  | ',
				' | \ | ',
				' |  \| ',
				'       ',
		),
	'O'=>array(	'  ___  ',
				' /   \ ',
				' |   | ',
				' |   | ',
				' \___/ ',
		),
	'P'=>array(	' ____  ',
				' |   | ',
				' |__/  ',
				' |     ',
				' |     ',
		),
	'Q'=>array(	'   __   ',
				'  /  \  ',
				' |    | ',
				' |   \| ',
				'  \__/\ ',
		),
	'R'=>array(	'  ___  ',
				' |   | ',
				' |__/  ',
				' |  \  ',
				' |   \ ',
		),
	'S'=>array(	'  ___  ',
				' |     ',
				' \___  ',
				'     | ',
				' ___/  ',
		),
	'T'=>array(	' _____ ',
				'   |   ',
				'   |   ',
				'   |   ',
				'   |   ',
		),
	'U'=>array(	' |   | ',
				' |   | ',
				' |   | ',
				' |   |',
				' \___/ ',
		),
	'V'=>array(	' \   / ',
				' \   / ',
				'  \ /  ',
				'  \ /  ',
				'   V   ',
		),
	'W'=>array(	' |   | ',
				' |   | ',
				' | | | ',
				' | A | ',
				' \/ \/ ',
		),
	'X'=>array(	' \   / ',
				'  \ /  ',
				'   X   ',
				'  / \  ',
				' /   \ ',
		),
	'Y'=>array(	' \   / ',
				'  \ /  ',
				'   Y   ',
				'   |   ',
				'   |   ',
		),
	'Z'=>array(	' _____ ',
				'    /  ',
				'   /   ',
				'  /    ',
				' /____ ',
		),
	'.'=>array(	'   ',
				'   ',
				'   ',
				'   ',
				' 0 ',
		),
		
	'+'=>array(	'       ',
				'   +   ',
				' +++++ ',
				'   +   ',
				'       ',
		),
	'-'=>array(	'       ',
				'       ',
				' ----- ',
				'       ',
				'       ',
		),
	'='=>array(	'      ',
				'      ',
				' ==== ',
				' ==== ',
				'      ',
		),
	'_'=>array(	'      ',
				'      ',
				'      ',
				'      ',
				'______',
		),
	'unknownchar'=>array(	' _____  ',
					'|     | ',
					'| unk | ',
					'| chr | ',
					'|_____| ',
		),


);

$vars[DSE][FontChars2]=array(
	'A'=>array(	'   AA   ',
				'  A  A  ',
				'  AaaA  ',
				' AA  AA ',
				' A    A ',
		),
	'B'=>array(	' BBBb  ',
				' B   B ',
				' BBBB  ',
				' B   B ',
				' BBBB  ',
		),
	'C'=>array(	'  cCc  ',
				' C   C ',
				' C     ',
				' C   c ',
				'  CCC  ',
		),
	'D'=>array(	' DDDD  ',
				' D   D ',
				' D   D ',
				' D   D ',
				' DDDD  ',
		),
	'E'=>array(	' EEEEE ',
				' E     ',
				' EEEE  ',
				' E     ',
				' EEEEE ',
		),
	'F'=>array(	' FFFFF ',
				' F     ',
				' FFFF  ',
				' F     ',
				' F     ',
		),
	'G'=>array(	'  gGgg  ',
				' G      ',
				' G  GGG ',
				' G   G  ',
				'  GGG   ',
		),
	'H'=>array(	' H   H ',
				' H   H ',
				' HHHHH ',
				' H   H ',
				' H   H ',
		),
	'I'=>array(	' III ',
				'  I  ',
				'  I  ',
				'  I  ',
				' III ',
		),
	'J'=>array(	'    JJ ',
				'     J ',
				'     J ',
				' J   J ',
				'  JJJ  ',
		),
	'K'=>array(	' K  K ',
				' K K  ',
				' KK   ',
				' K K  ',
				' K  K ',
		),
	'L'=>array(	' L    ',
				' L    ',
				' L    ',
				' L    ',
				' LLLL ',
		),
	'M'=>array(	' M   M ',
				' MM MM ',
				' M M M ',
				' M   M ',
				' M   M ',
		),
	'N'=>array(	' N   N ',
				' NN  N ',
				' N N N ',
				' N  NN ',
				' N   N ',
		),
	'O'=>array(	'  oOo  ',
				' O   O ',
				' O   O ',
				' O   O ',
				'  OOO  ',
		),
	'P'=>array(	' PPPPp ',
				' P   P ',
				' PPPP  ',
				' P     ',
				' P     ',
		),
	'Q'=>array(	'  qQq  ',
				' Q   Q ',
				' Q q Q ',
				' Q  QQ ',
				'  QQQ Q',
		),
	'R'=>array(	' RRRR  ',
				' R   R ',
				' RRRR  ',
				' R  R  ',
				' R   R ',
		),
	'S'=>array(	'  sSSs ',
				' S     ',
				'  SSs  ',
				'     S ',
				' sSSS  ',
		),
	'T'=>array(	' TTTTT ',
				'   T   ',
				'   T   ',
				'   T   ',
				'   T   ',
		),
	'U'=>array(	' U   U ',
				' U   U ',
				' U   U ',
				' U   U ',
				'  UUU  ',
		),
	'V'=>array(	' V   V ',
				' V   V ',
				'  V V  ',
				'  V V  ',
				'   V   ',
		),
	'W'=>array(	' W   W ',
				' W   W ',
				' W W W ',
				' W W W ',
				' WW WW ',
		),
	'X'=>array(	' X   X ',
				'  X X  ',
				'   X   ',
				'  X X  ',
				' X   X ',
		),
	'Y'=>array(	' Y   Y ',
				'  Y Y  ',
				'   Y   ',
				'   Y   ',
				'   Y   ',
		),
	'Z'=>array(	' ZZZZZ ',
				'    Z  ',
				'   Z   ',
				'  Z    ',
				' ZZZZZ ',
		),
	'.'=>array(	'   ',
				'   ',
				'   ',
				'   ',
				' 0 ',
		),
		
	'+'=>array(	'       ',
				'   +   ',
				' +++++ ',
				'   +   ',
				'       ',
		),
	'-'=>array(	'       ',
				'       ',
				' ----- ',
				'       ',
				'       ',
		),
	'='=>array(	'      ',
				'      ',
				' ==== ',
				' ==== ',
				'      ',
		),
	'_'=>array(	'      ',
				'      ',
				'      ',
				'      ',
				'______',
		),
	'unknownchar'=>array(	' _____  ',
					'|     | ',
					'| unk | ',
					'| chr | ',
					'|_____| ',
		),


);

function dse_font_2_cli($Message,$Return=FALSE){
	global $vars;
	$Message=strtoupper($Message);
	$tbr=array();
	for($i=0;$i<strlen($Message);$i++){
		$c=$Message[$i];
		//print "c=$c ";
		if(!array_key_exists($c, $vars[DSE][FontChars])){
			$c="unknownchar";
		}
		for($L=0;$L<5;$L++){
			$tbr[$L].=$vars[DSE][FontChars][$c][$L]."";
		}		
	}
	if($Return){
		return $tbr;
	}
	for($L=0;$L<5;$L++){
		print $tbr[$L]."\n";
	}
}



?>
